CANONICAL_DATA_MODEL_MONTHS = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
]
CANONICAL_DATA_MODEL_DATEFORMAT = "%d.%m.%Y"
CANONICAL_DATA_MODEL_TRANSACTION_TYPES = ["Einnahme", "Ausgabe", "Umbuchung"]
CANONICAL_DATA_MODEL_CATEGORIES = [
    "Business",
    "Einkaufen",
    "Entertainment",
    "Essen",
    "Gebühren",
    "Geschenk",
    "Kleidung",
    "Learning",
    "Learning: Books",
    "Lohn/Gehalt",
    "Misc",
    "Mobilitaet",
    "Nebenjob",
    "Reisen",
    "Sparen",
    "Studium",
    "Umbuchung",
    "Unterhalt",
    "Verein",
    "Versicherung",
    "Wohnen",
    "Wohnen: NK",
    "Zuwendung",
    "NOT ASSIGNED",
]
CANONICAL_DATA_MODEL_ACCOUNTS = ["DKB", "AMEX", "PP", "CASH", "MM"]
